version: '3'
services:
    auth:
        build: .
    nginx:
        image: nginx:latest
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - auth
        ports: 
            - 3000:80