name: backend/class

on:
  push:
    branches: [ master, staging ]
    paths:
      - 'backend/class/**'

jobs:
  build-containers:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
       
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}   
      run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    # Build backend services
    - name: Build class
      run: |
        docker build ./backend/class -t zefryuuko/wads-class:latest
    
    # Push to Docker Hub
    - name: Push to Docker Hub
      run: |
        docker push zefryuuko/wads-class:latest
